services:

  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true
    network_mode: host

  db_vector:
    image: qdrant/qdrant
    container_name: qdrant
    restart: on-failure
    volumes:
      - ./db/qdrant:/qdrant/storage
    ports:
      - 6333:6333
    expose:
      - 6333
